development:
  dialect: postgres
  database: linkin_development
  user: Martin
  password: 
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://Martin@127.0.0.1:5432/linkin_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://Martin@127.0.0.1:5432/linkin_production?sslmode=disable"}}